name: opengate_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - scipy
  - pandas
  - uproot
  - awkward-array
  - jupyter
  - ipywidgets
  - pip
  - pip:
    - opengate==10.0.3
    - gatetools
    - pydicom
    - pyvista
    - tqdm
    - loguru
    - radioactivedecay
    - spekpy
